<section>
    <h3>Logowanie</h3>
    <form>
        <div class="input_wrapping">
            <label>
                nick
                <input type="text" name="nick-name">
            </label>
        </div>
        <div class="input_wrapping">
        <label>
            hasło
            <input type="password" name="password-name">
        </label>
        </div>
        <input type="button" name="login-name" value="login-value">
    </form>
</section>