<section>
    <h3>Logowanie</h3>
    <form action="/Auth/login" method="post">
        <div class="input_wrapping">
            <label>
                nick
                <input type="text" name="nick">
            </label>
        </div>
        <div class="input_wrapping">
        <label>
            hasło
            <input type="password" name="password">
        </label>
        </div>
        <input type="submit" name="login" value="Loguj">
    </form>
</section>