<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8"/>
    <meta name="application-name" content="a simple web application using templates, can be offline and database"/>
    <meta name="description" content="cellular automaton, the game of life with ability to record your own simulation"/>
    <meta name="keywords" content="phtml, templates, database, offline, registration, TI, gr. czwartkowa"/>
    <meta name="author" content="Dawid Karminski"/>


    <title><!-- TODO deklaracje zmiennej php do wstawiania tytułu --></title>

    <!-- tutaj include'owane sa pliki js -->
    <!-- TODO deklaracje zmiennej php do wstawiania js -->
    <!-- tutaj include'owane sa pliki css -->
    <!-- TODO deklaracje zmiennej php do wstawiania css -->

</head>

<body>

<!-- HEADER -->
<header>
    <h1>Gra w życie</h1>
    <h2>Automat komórkowy</h2>
</header>

<!-- NAV -->
<nav>
    <ul>
        <!-- TODO deklaracje zmiennej php do wstawiania paska nawigacji -->
    </ul>
</nav>

<!-- MAIN -->
<main>




</main>

<!-- FOOTER -->
<footer>
    <p><small>Dawid Karmiński</small></p>
    <p><small>Fizyka Techniczna</small></p>
    <p><small>WFiIS</small></p>
    <p><small>Drugi projekt na przedmiot TI</small></p>
</footer>
</body>

</html>
