<section>
    <h3>Rejestracja</h3>
    <form>
        <div class="input_wrapping">
            <label>
                adres e-mail
                <input type="email" name="email">
            </label>
            <label>
                powtórz adres e-mail
                <input type="email" name="email_repeat">
            </label>
        </div>
        <div class="input_wrapping">
            <label>
                nick
                <input type="text" name="nick">
            </label>
        </div>
        <div class="input_wrapping">
            <label>
                hasło
                <input type="password" name="password">
            </label>
            <label>
                powtórz hasło
                <input type="password" name="password_repeat">
            </label>
        </div>
        <input type="button" name="registration-name" value="Rejestruj">
    </form>
</section>