<section>
    <h3>Rejestracja</h3>
    <form>
        <div class="input_wrapping">
            <label>
                adres e-mail
                <input type="email" name="email-name">
            </label>
            <label>
                powtórz adres e-mail
                <input type="email" name="email_repeat-name">
            </label>
        </div>
        <div class="input_wrapping">
            <label>
                nick
                <input type="text" name="nick-name">
            </label>
        </div>
        <div class="input_wrapping">
            <label>
                hasło
                <input type="password" name="password-name">
            </label>
            <label>
                powtórz hasło
                <input type="password" name="password_repeat-name">
            </label>
        </div>
        <input type="button" name="registration-name" value="registration">
    </form>
</section>